# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import weather_pb2 as weather__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in weather_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventSubscriptionServiceStub(object):
    """The gRPC service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_stream(
                '/eventsubscription.EventSubscriptionService/Subscribe',
                request_serializer=weather__pb2.SubscriptionRequest.SerializeToString,
                response_deserializer=weather__pb2.EventNotification.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/eventsubscription.EventSubscriptionService/Unsubscribe',
                request_serializer=weather__pb2.UnsubscriptionRequest.SerializeToString,
                response_deserializer=weather__pb2.UnsubscriptionResponse.FromString,
                _registered_method=True)


class EventSubscriptionServiceServicer(object):
    """The gRPC service definition.
    """

    def Subscribe(self, request, context):
        """Subscribe to events. Server streams notifications.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Unsubscribe from events. Unary call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventSubscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=weather__pb2.SubscriptionRequest.FromString,
                    response_serializer=weather__pb2.EventNotification.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=weather__pb2.UnsubscriptionRequest.FromString,
                    response_serializer=weather__pb2.UnsubscriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eventsubscription.EventSubscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eventsubscription.EventSubscriptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventSubscriptionService(object):
    """The gRPC service definition.
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/eventsubscription.EventSubscriptionService/Subscribe',
            weather__pb2.SubscriptionRequest.SerializeToString,
            weather__pb2.EventNotification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventsubscription.EventSubscriptionService/Unsubscribe',
            weather__pb2.UnsubscriptionRequest.SerializeToString,
            weather__pb2.UnsubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
